---
specfile_path: hello.spec
synced_files:
  - hello.spec
upstream_package_name: hello
downstream_package_name: hello
# actions:
#   post-upstream-clone: "python3 setup.py sdist --dist-dir ."
# current_version_command: ["python3", "setup.py", "--version"]
# create_tarball_command: ["python3", "setup.py", "sdist", "--dist-dir", "."]
jobs:
- job: copr_build
  trigger: pull_request
  metadata:
    targets:
    - fedora-all-x86_64
    - fedora-all-aarch64

- job: copr_build
  trigger: release
  metadata:
    targets:
    - fedora-all-x86_64
    - fedora-all-aarch64

- job: propose_downstream
  trigger: release
  metadata:
    dist-git-branch: fedora-all
