---
packit_instances: ["prod", "stg"]
specfile_path: hello.spec
synced_files:
  - hello.spec
upstream_package_name: hello
downstream_package_name: hello
# actions:
#   post-upstream-clone: "python3 setup.py sdist --dist-dir ."
# current_version_command: ["python3", "setup.py", "--version"]
# create_tarball_command: ["python3", "setup.py", "sdist", "--dist-dir", "."]
jobs:
- job: copr_build
  trigger: pull_request
  project: testing-project-for-packit-4
  owner: lachmanfrantisek
  targets:
  - fedora-rawhide-x86_64

- job: copr_build
  trigger: release
  metadata:
    targets:
    - fedora-stable

- job: copr_build
  trigger: commit
  metadata:
    branch: main
    targets:
      - fedora-stable

- job: propose_downstream
  trigger: release
  packit_instances: ["stg"]
  metadata:
    dist_git_branches:
    - fedora-all
