---
packit_instances: ["prod", "stg"]
specfile_path: hello.spec
files_to_sync:
  - .packit.yaml
  - hello.spec
upstream_package_name: hello
downstream_package_name: hello
# actions:
#   post-upstream-clone: "python3 setup.py sdist --dist-dir ."
# current_version_command: ["python3", "setup.py", "--version"]
# create_tarball_command: ["python3", "setup.py", "sdist", "--dist-dir", "."]
jobs:
- job: copr_build
  trigger: pull_request
  targets:
  - fedora-rawhide-x86_64
  branch: main