---
packages:

  hello:
    downstream_package_name: hello
    upstream_package_name: hello
    paths: 
      - ./hello
    specfile_path: hello.spec
    files_to_sync: 
      - hello.spec

  world:
    downstream_package_name: world
    upstream_package_name: world
    paths: 
      - ./world
    specfile_path: world.spec
    files_to_sync: 
      - world.spec

jobs:
- job: copr_build
  trigger: pull_request
  packages:
  - hello
  - world
  targets:
  - fedora-rawhide

- job: copr_build
  trigger: pull_request
  packages:
  - hello
  targets:
  - fedora-37

- job: copr_build
  trigger: pull_request
  packages:
  - world
  targets:
  - fedora-38
