---
packit_instances: ["stg"]
specfile_path: hello.spec
synced_files:
  - hello.spec
upstream_package_name: hello
downstream_package_name: hello
# actions:
#   post-upstream-clone: "python3 setup.py sdist --dist-dir ."
# current_version_command: ["python3", "setup.py", "--version"]
# create_tarball_command: ["python3", "setup.py", "sdist", "--dist-dir", "."]

release_suffix: "someTests"

jobs:
- job: copr_build
  trigger: pull_request
  release_suffix: null
  project: yikes
  owner: mfocko

- job: copr_build
  trigger: release

- job: copr_build
  trigger: commit
  branch: main

