---
packit_instances: ["stg"]
specfile_path: hello.spec
files_to_sync:
  - .packit.yaml
  - hello.spec
upstream_package_name: hello
downstream_package_name: hello

test_command:
  default_identifier: inspect

jobs:
- job: copr_build
  trigger: pull_request
  targets:
  - fedora-rawhide-x86_64

- job: tests
  manual_trigger: true
  labels:
    - inspect
  identifier: inspect
  trigger: pull_request
  fmf_url: https://github.com/packit/tmt-plans
  fmf_ref: main
  tmt_plan: "/plans/rpminspect"
  targets:
    - fedora-rawhide-x86_64

- job: tests
  manual_trigger: true
  labels:
    - lint
  identifier: lint
  trigger: pull_request
  fmf_url: https://github.com/packit/tmt-plans
  fmf_ref: main
  tmt_plan: "/plans/rpmlint"
  targets:
    - fedora-rawhide-x86_64