---
packit_instances: ["stg"]

jobs:
- job: copr_build
  trigger: pull_request
  targets:
  - fedora-39-x86_64

- job: vm_image_build
  trigger: pull_request
  copr_chroot: fedora-39-x86_64
  image_request:
    architecture: x86_64
    image_type: aws
    upload_request:
      type: aws
      options:
        share_with_accounts:
        - "727920394381" # ARR
  image_customizations:
    packages: [hello-world]
  image_distribution: fedora-39
