---
specfile_path: hello.spec
synced_files:
  - hello.spec
upstream_package_name: hello
downstream_package_name: hello
actions:
  create-archive:
  - python3 setup.py sdist --dist-dir .
  - bash -c 'echo hello-$(python3 setup.py --version).tar.gz'
jobs:
- job: copr_build
  trigger: pull_request
  metadata:
    targets:
    - fedora-stable-x86_64
    - fedora-rawhide-x86_64

- job: copr_build
  trigger: release
  metadata:
    targets:
    - fedora-stable

- job: tests
  trigger: pull_request
  metadata:
    targets:
    - fedora-stable-x86_64
    - fedora-rawhide-x86_64

- job: propose_downstream
  trigger: release
  metadata:
    dist-git-branch: fedora-all
