---
# actions:
#   post-upstream-clone: "python3 setup.py sdist --dist-dir ."
# current_version_command: ["python3", "setup.py", "--version"]
# create_tarball_command: ["python3", "setup.py", "sdist", "--dist-dir", "."]
jobs:
- job: tests
  trigger: pull_request
  metadata:
    targets:
    - fedora-stable-x86_64
    - centos-stream-8-x86_64
    skip_build: true

