---
specfile_path: hello.spec
synced_files:
  - hello.spec
upstream_package_name: hello
# actions:
#   post-upstream-clone: "python3 setup.py sdist --dist-dir ."
# current_version_command: ["python3", "setup.py", "--version"]
# create_tarball_command: ["python3", "setup.py", "sdist", "--dist-dir", "."]
jobs:
- job: copr_build
  trigger: pull_request
  metadata:
    owner: "rolivier"
    project: "leapp-packit-poc"
    targets:
    - fedora-stable-x86_64
    - fedora-rawhide-x86_64

- job: copr_build
  trigger: commit
  metadata:
    owner: "rolivier"
    project: "leapp-packit-poc"
    targets:
    - fedora-stable-x86_64
    - fedora-rawhide-x86_64

- job: tests
  trigger: pull_request
  identifier: tests-7to8
  metadata:
    targets:
    - fedora-stable-x86_64
    - fedora-rawhide-x86_64
    use_internal_tf: True

- job: tests
  trigger: pull_request
  identifier: tests-8to9
  metadata:
    targets:
    - fedora-stable-x86_64
    - fedora-rawhide-x86_64
    use_internal_tf: True
