---
packit_instances: ["prod"]
specfile_path: hello-world.spec
files_to_sync:
  - .packit.yaml
  - hello-world.spec
upstream_package_name: hello
downstream_package_name: hello
# actions:
#   post-upstream-clone: "python3 setup.py sdist --dist-dir ."
# current_version_command: ["python3", "setup.py", "--version"]
# create_tarball_command: ["python3", "setup.py", "sdist", "--dist-dir", "."]
jobs:
- job: copr_build
  trigger: pull_request
  targets:
  - fedora-38-x86_64

- job: vm_image_build
  trigger: pull_request
  image_request:
    architecture: x86_64
    image_type: aws
    upload_request:
      type: aws
      options:
        share_with_accounts:
        - "727920394381" # ARR
        - "125523088429" # Testing Farm
  image_customizations:
    packages: [hello-world]
  image_distribution: fedora-38
  copr_chroot: fedora-38-x86_64


