---
packit_instances: ["prod", "stg"]
specfile_path: hello.spec
synced_files:
  - hello.spec
upstream_package_name: hello
downstream_package_name: hello
# actions:
#   post-upstream-clone: "python3 setup.py sdist --dist-dir ."
# current_version_command: ["python3", "setup.py", "--version"]
# create_tarball_command: ["python3", "setup.py", "sdist", "--dist-dir", "."]
jobs:
- job: copr_build
  trigger: pull_request
  metadata:
    targets:
    - fedora-all

- job: copr_build
  trigger: release
  metadata:
    targets:
    - fedora-stable

- job: copr_build
  trigger: commit
  metadata:
    branch: main
    targets:
      - fedora-stable

- job: tests
  trigger: pull_request
  use_internal_tf: True
  targets:
    epel-7-x86_64:
      distros: [RHEL-7.9-ZStream]

- job: propose_downstream
  trigger: release
  packit_instances: ["stg"]
  metadata:
    dist-git-branch: fedora-all
