---
specfile_path: hello.spec
synced_files:
  - hello.spec
upstream_package_name: hello
downstream_package_name: hello

actions:
  get-current-version:

# actions:
#   post-upstream-clone: "python3 setup.py sdist --dist-dir ."
# current_version_command: ["python3", "setup.py", "--version"]
# create_tarball_command: ["python3", "setup.py", "sdist", "--dist-dir", "."]
jobs:
- job: copr_build
  trigger: pull_request
  metadata:
    targets:
    - fedora-stable-x86_64

- job: copr_build
  trigger: release
  metadata:
    targets:
    - fedora-stable

- job: copr_build
  trigger: commit
  metadata:
    branch: main
    targets:
      - fedora-stable

- job: tests
  trigger: pull_request
  metadata:
    targets:
    - fedora-stable-x86_64

- job: propose_downstream
  trigger: release
  metadata:
    dist_git_branches:
    - fedora-all
