---
packit_instances: ["prod", "stg"]
specfile_path: hello.spec
files_to_sync:
  - .packit.yaml
  - hello.spec
upstream_package_name: hello
downstream_package_name: hello
# actions:
#   post-upstream-clone: "python3 setup.py sdist --dist-dir ."
# current_version_command: ["python3", "setup.py", "--version"]
# create_tarball_command: ["python3", "setup.py", "sdist", "--dist-dir", "."]

jobs:
- job: copr_build
  trigger: release
  targets:
  - fedora-stable

- job: copr_build
  trigger: commit
  branch: main
  targets:
    - fedora-stable

- job: copr_build
  trigger: pull_request
  targets:
  - fedora-37
  - fedora-38

- job: tests
  trigger: pull_request
  targets:
  - fedora-37
  tf_extra_params:
    environments:
      - os: null
        variables:
          IMAGE: fedora:37

- job: tests
  trigger: pull_request
  targets:
  - fedora-38
  skip_build: true
  tf_extra_params:
    environments:
      - os: null
        variables:
          IMAGE: fedora:38
