---
specfile_path: hello.spec
synced_files:
  - hello.spec
upstream_package_name: hello
downstream_package_name: hello

jobs:
- job: copr_build
  trigger: pull_request
  metadata:
    targets:
    - fedora-all

- job: copr_build
  trigger: commit
  metadata:
    branch: main
    targets:
      - fedora-rawhide-x86_64

