---
specfile_path: hello.spec
synced_files:
  - hello.spec
upstream_package_name: hello
downstream_package_name: hello
# actions:
#   post-upstream-clone: "python3 setup.py sdist --dist-dir ."
# current_version_command: ["python3", "setup.py", "--version"]
# create_tarball_command: ["python3", "setup.py", "sdist", "--dist-dir", "."]
jobs:
- job: copr_build
  trigger: pull_request
  metadata:
    targets:
      - fedora-35-x86_64
      - epel-8-x86_64

- job: tests
  trigger: pull_request
  metadata:
    targets:
      fedora-35-x86_64:
        distros: [fedora-35, fedora-36]
      epel-8-x86_64:
        distros: [centos-stream-8]

- job: propose_downstream
  trigger: release
  metadata:
    dist_git_branches:
    - fedora-all
