---
specfile_path: hello.spec
synced_files:
  - hello.spec
upstream_package_name: hello
downstream_package_name: hello
# actions:
#   post-upstream-clone: "python3 setup.py sdist --dist-dir ."
# current_version_command: ["python3", "setup.py", "--version"]
# create_tarball_command: ["python3", "setup.py", "sdist", "--dist-dir", "."]
packit_instances: ["stg"]
jobs:

- job: tests
  trigger: pull_request
  skip_build: true
  targets:
  - fedora-rawhide-x86_64
  - epel-8

- job: tests
  trigger: pull_request
  identifier: first
  skip_build: true
  targets:
  - fedora-rawhide-x86_64

- job: tests
  trigger: pull_request
  identifier: second
  skip_build: true
  targets:
  - fedora-rawhide-x86_64


