---
packit_instances: ["stg", "prod"]
specfile_path: hello.spec
synced_files:
  - hello.spec
upstream_package_name: hello
downstream_package_name: hello
# actions:
#   post-upstream-clone: "python3 setup.py sdist --dist-dir ."
# current_version_command: ["python3", "setup.py", "--version"]
# create_tarball_command: ["python3", "setup.py", "sdist", "--dist-dir", "."]
jobs:
- job: copr_build
  trigger: pull_request
  metadata:
    targets:
    - fedora-stable-x86_64
    - fedora-rawhide-x86_64

- job: tests
  trigger: pull_request
  identifier: test1
  metadata:
    targets:
    - fedora-stable-x86_64
    - fedora-rawhide-x86_64