---
packit_instances: ["prod", "stg"]
specfile_path: hello.spec
files_to_sync:
  - .packit.yaml
  - hello.spec
upstream_package_name: hello
downstream_package_name: hello
# actions:
#   post-upstream-clone: "python3 setup.py sdist --dist-dir ."
# current_version_command: ["python3", "setup.py", "--version"]
# create_tarball_command: ["python3", "setup.py", "sdist", "--dist-dir", "."]
jobs:
- job: copr_build
  trigger: pull_request
  targets:
  - fedora-all

- job: copr_build
  trigger: release
  targets:
  - fedora-stable

- job: copr_build
  trigger: commit
  branch: main
  targets:
    - fedora-stable

- job: tests
  trigger: pull_request
  targets:
  - fedora-all
  use_internal_tf: True

- job: propose_downstream
  trigger: release
  packit_instances: ["stg"]
  dist_git_branches:
  - fedora-all
