---
packit_instances: ["stg"]
specfile_path: hello.spec
synced_files:
  - hello.spec
upstream_package_name: hello
downstream_package_name: hello
actions:
  post-upstream-clone: "bla bla"

jobs:
- job: build
  trigger: pull_request
  metadata:
    targets:
    - fedora-rawhide-x86_64
