---
packit_instances: ["stg"]
specfile_path: hello.spec
synced_files:
  - hello.spec
upstream_package_name: hello
downstream_package_name: hello
actions:
  post-upstream-clone: "bla bla"

jobs:
- job: production_build
  trigger: pull_request
  targets:
  - fedora-rawhide-x86_64
  scratch: true
